#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Mac OS X Big Sur" --class osx --class darwwin --class os {
    savedefault
    insmod part_gpt
    insmod hfsplus
    set root='(hd1,gpt1)'
    search --no-floppy --fs-uuid --set=root 67E3-17ED
    chainloader /EFI/BOOT/Bootx64.efi
}
